### ISSUE TITLE
OCP 7.7.1.x Support

### ISSUE THREAD

**Issue by jmwright** [jmwright/ocp-build-system#15]
@fpq473 It looks like we're having glibc compatibility issues again.

https://github.com/CadQuery/ocp-build-system/actions/runs/5577613766/jobs/10190618029

**Comment by fpq473** [comment]
@jmwright I think it's the issue described in https://github.com/CadQuery/ocp-build-system/issues/12#issuecomment-1464495930.

Basically, the conda-forge `occt` package is being built with a toolchain that is too new for `manylinux_2_31`.  The last time we released 7.7.0, we had to pin the occt package to the build right before the toolchain was updated.  I think all builds of occt 7.7.1 are with the new toolchain.

It might be possible to make `manylinux_2_35` wheels (Fedora 36+, Ubuntu 22.04+) without much effort.  The alternative is to set up a separate build of occt (like you did with vtk), but that might be _a lot_ of work...

**Comment by fpq473** [comment]
@jmwright I see.  Unfortunately, `setup.py` is hard-coded to run in a conda environment (e.g. specific location of libraries, license files), so yes, it is probably more work to adapt it to produce a manylinux wheel from a bespoke occt installation.  (Possibly OCP would have to be built as well, and other dependencies.)

I'm not too engaged with OCP stuff right now (trying to transition to FreeCAD) so I can't offer much energy here.  I should be around to explain what `setup.py` is doing though, in case that's helpful.

**Comment by jmwright** [comment]
@fpq473 I ended up increasing the manylinux version. Thanks!
